INSERT INTO possible_countries(country,population) VALUES ('Afghanistan',37172386);
INSERT INTO possible_countries(country,population) VALUES ('Albania',2866376);
INSERT INTO possible_countries(country,population) VALUES ('Algeria',42228429);
INSERT INTO possible_countries(country,population) VALUES ('American Samoa',55465);
INSERT INTO possible_countries(country,population) VALUES ('Andorra',77006);
INSERT INTO possible_countries(country,population) VALUES ('Angola',30809762);
INSERT INTO possible_countries(country,population) VALUES ('Anguilla',15094);
INSERT INTO possible_countries(country,population) VALUES ('Antarctica',1106);
INSERT INTO possible_countries(country,population) VALUES ('Antigua and Barbuda',96286);
INSERT INTO possible_countries(country,population) VALUES ('Argentina',44494502);
INSERT INTO possible_countries(country,population) VALUES ('Armenia',2951776);
INSERT INTO possible_countries(country,population) VALUES ('Aruba',105845);
INSERT INTO possible_countries(country,population) VALUES ('Australia',24982688);
INSERT INTO possible_countries(country,population) VALUES ('Austria',8840521);
INSERT INTO possible_countries(country,population) VALUES ('Azerbaijan',9939800);
INSERT INTO possible_countries(country,population) VALUES ('Bahamas',385640);
INSERT INTO possible_countries(country,population) VALUES ('Bahrain',1569439);
INSERT INTO possible_countries(country,population) VALUES ('Bangladesh',161356039);
INSERT INTO possible_countries(country,population) VALUES ('Barbados',286641);
INSERT INTO possible_countries(country,population) VALUES ('Belarus',9483499);
INSERT INTO possible_countries(country,population) VALUES ('Belgium',11433256);
INSERT INTO possible_countries(country,population) VALUES ('Belize',383071);
INSERT INTO possible_countries(country,population) VALUES ('Benin',11485048);
INSERT INTO possible_countries(country,population) VALUES ('Bermuda',63973);
INSERT INTO possible_countries(country,population) VALUES ('Bhutan',754394);
INSERT INTO possible_countries(country,population) VALUES ('Bolivia',11353142);
INSERT INTO possible_countries(country,population) VALUES ('Bosnia and Herzegovina',3323929);
INSERT INTO possible_countries(country,population) VALUES ('Botswana',2254126);
INSERT INTO possible_countries(country,population) VALUES ('Bouvet Island',0);
INSERT INTO possible_countries(country,population) VALUES ('Brazil',209469333);
INSERT INTO possible_countries(country,population) VALUES ('British Indian Ocean Territory',0);
INSERT INTO possible_countries(country,population) VALUES ('Brunei',428962);
INSERT INTO possible_countries(country,population) VALUES ('Bulgaria',7025037);
INSERT INTO possible_countries(country,population) VALUES ('Burkina Faso',19751535);
INSERT INTO possible_countries(country,population) VALUES ('Burundi',11175378);
INSERT INTO possible_countries(country,population) VALUES ('Cabo Verde',555987);
INSERT INTO possible_countries(country,population) VALUES ('Cambodia',16249798);
INSERT INTO possible_countries(country,population) VALUES ('Cameroon',25216237);
INSERT INTO possible_countries(country,population) VALUES ('Canada',37057765);
INSERT INTO possible_countries(country,population) VALUES ('Cape Verde',543767);
INSERT INTO possible_countries(country,population) VALUES ('Cayman Islands',64174);
INSERT INTO possible_countries(country,population) VALUES ('Central African Republic',4666377);
INSERT INTO possible_countries(country,population) VALUES ('Chad',15477751);
INSERT INTO possible_countries(country,population) VALUES ('Chile',18729160);
INSERT INTO possible_countries(country,population) VALUES ('China',1392730000);
INSERT INTO possible_countries(country,population) VALUES ('Christmas Island',1402);
INSERT INTO possible_countries(country,population) VALUES ('Cocos (Keeling) Islands',596);
INSERT INTO possible_countries(country,population) VALUES ('Colombia',49648685);
INSERT INTO possible_countries(country,population) VALUES ('Comoros',832322);
INSERT INTO possible_countries(country,population) VALUES ('Congo',5244363);
INSERT INTO possible_countries(country,population) VALUES ('Cook Islands',17379);
INSERT INTO possible_countries(country,population) VALUES ('Costa Rica',4999441);
INSERT INTO possible_countries(country,population) VALUES ('Croatia',4087843);
INSERT INTO possible_countries(country,population) VALUES ('Cuba',11338138);
INSERT INTO possible_countries(country,population) VALUES ('Cyprus',1189265);
INSERT INTO possible_countries(country,population) VALUES ('Czech Republic',10629928);
INSERT INTO possible_countries(country,population) VALUES ('Denmark',5793636);
INSERT INTO possible_countries(country,population) VALUES ('Djibouti',958920);
INSERT INTO possible_countries(country,population) VALUES ('Dominica',71625);
INSERT INTO possible_countries(country,population) VALUES ('Dominican Republic',10627165);
INSERT INTO possible_countries(country,population) VALUES ('East Timor',1267972);
INSERT INTO possible_countries(country,population) VALUES ('Ecuador',17084357);
INSERT INTO possible_countries(country,population) VALUES ('Egypt',98423595);
INSERT INTO possible_countries(country,population) VALUES ('El Salvador',6420744);
INSERT INTO possible_countries(country,population) VALUES ('England',55619400);
INSERT INTO possible_countries(country,population) VALUES ('Equatorial Guinea',1308974);
INSERT INTO possible_countries(country,population) VALUES ('Eritrea',6213972);
INSERT INTO possible_countries(country,population) VALUES ('Estonia',1321977);
INSERT INTO possible_countries(country,population) VALUES ('Ethiopia',109224559);
INSERT INTO possible_countries(country,population) VALUES ('Falkland Islands',2840);
INSERT INTO possible_countries(country,population) VALUES ('Faroe Islands',48497);
INSERT INTO possible_countries(country,population) VALUES ('Fiji Islands',883483);
INSERT INTO possible_countries(country,population) VALUES ('Finland',5515525);
INSERT INTO possible_countries(country,population) VALUES ('France',66977107);
INSERT INTO possible_countries(country,population) VALUES ('French Guiana',290691);
INSERT INTO possible_countries(country,population) VALUES ('French Polynesia',277679);
INSERT INTO possible_countries(country,population) VALUES ('French Southern territories',0);
INSERT INTO possible_countries(country,population) VALUES ('Gabon',2119275);
INSERT INTO possible_countries(country,population) VALUES ('Gambia',2280102);
INSERT INTO possible_countries(country,population) VALUES ('Georgia',3726549);
INSERT INTO possible_countries(country,population) VALUES ('Germany',82905782);
INSERT INTO possible_countries(country,population) VALUES ('Ghana',29767108);
INSERT INTO possible_countries(country,population) VALUES ('Gibraltar',33718);
INSERT INTO possible_countries(country,population) VALUES ('Greece',10731726);
INSERT INTO possible_countries(country,population) VALUES ('Greenland',56025);
INSERT INTO possible_countries(country,population) VALUES ('Grenada',111454);
INSERT INTO possible_countries(country,population) VALUES ('Guadeloupe',395700);
INSERT INTO possible_countries(country,population) VALUES ('Guam',165768);
INSERT INTO possible_countries(country,population) VALUES ('Guatemala',17247807);
INSERT INTO possible_countries(country,population) VALUES ('Guinea',12414318);
INSERT INTO possible_countries(country,population) VALUES ('Guinea-Bissau',1874309);
INSERT INTO possible_countries(country,population) VALUES ('Guyana',779004);
INSERT INTO possible_countries(country,population) VALUES ('Haiti',11123176);
INSERT INTO possible_countries(country,population) VALUES ('Heard Island and McDonald Islands',0);
INSERT INTO possible_countries(country,population) VALUES ('Holy See (Vatican City State)',825);
INSERT INTO possible_countries(country,population) VALUES ('Honduras',9587522);
INSERT INTO possible_countries(country,population) VALUES ('Hong Kong',7451000);
INSERT INTO possible_countries(country,population) VALUES ('Hungary',9775564);
INSERT INTO possible_countries(country,population) VALUES ('Iceland',352721);
INSERT INTO possible_countries(country,population) VALUES ('India',1352617328);
INSERT INTO possible_countries(country,population) VALUES ('Indonesia',267663435);
INSERT INTO possible_countries(country,population) VALUES ('Iran',81800269);
INSERT INTO possible_countries(country,population) VALUES ('Iraq',38433600);
INSERT INTO possible_countries(country,population) VALUES ('Ireland',4867309);
INSERT INTO possible_countries(country,population) VALUES ('Israel',8882800);
INSERT INTO possible_countries(country,population) VALUES ('Italy',60421760);
INSERT INTO possible_countries(country,population) VALUES ('Ivory Coast',25069229);
INSERT INTO possible_countries(country,population) VALUES ('Jamaica',2934855);
INSERT INTO possible_countries(country,population) VALUES ('Japan',126529100);
INSERT INTO possible_countries(country,population) VALUES ('Jordan',9956011);
INSERT INTO possible_countries(country,population) VALUES ('Kazakhstan',18272430);
INSERT INTO possible_countries(country,population) VALUES ('Kenya',51393010);
INSERT INTO possible_countries(country,population) VALUES ('Kiribati',115847);
INSERT INTO possible_countries(country,population) VALUES ('Kuwait',4137309);
INSERT INTO possible_countries(country,population) VALUES ('Kyrgyzstan',6322800);
INSERT INTO possible_countries(country,population) VALUES ('Laos',7061507);
INSERT INTO possible_countries(country,population) VALUES ('Latvia',1927174);
INSERT INTO possible_countries(country,population) VALUES ('Lebanon',6848925);
INSERT INTO possible_countries(country,population) VALUES ('Lesotho',2108132);
INSERT INTO possible_countries(country,population) VALUES ('Liberia',4818977);
INSERT INTO possible_countries(country,population) VALUES ('Libyan Arab Jamahiriya',6678567);
INSERT INTO possible_countries(country,population) VALUES ('Liechtenstein',37910);
INSERT INTO possible_countries(country,population) VALUES ('Lithuania',2801543);
INSERT INTO possible_countries(country,population) VALUES ('Luxembourg',607950);
INSERT INTO possible_countries(country,population) VALUES ('Macao',631636);
INSERT INTO possible_countries(country,population) VALUES ('North Macedonia',2084367);
INSERT INTO possible_countries(country,population) VALUES ('Madagascar',26262368);
INSERT INTO possible_countries(country,population) VALUES ('Malawi',18143315);
INSERT INTO possible_countries(country,population) VALUES ('Malaysia',31528585);
INSERT INTO possible_countries(country,population) VALUES ('Maldives',515696);
INSERT INTO possible_countries(country,population) VALUES ('Mali',19077690);
INSERT INTO possible_countries(country,population) VALUES ('Malta',484630);
INSERT INTO possible_countries(country,population) VALUES ('Marshall Islands',58413);
INSERT INTO possible_countries(country,population) VALUES ('Martinique',376480);
INSERT INTO possible_countries(country,population) VALUES ('Mauritania',4403319);
INSERT INTO possible_countries(country,population) VALUES ('Mauritius',1265303);
INSERT INTO possible_countries(country,population) VALUES ('Mayotte',270372);
INSERT INTO possible_countries(country,population) VALUES ('Mexico',126190788);
INSERT INTO possible_countries(country,population) VALUES ('Micronesia, Federated States of',112640);
INSERT INTO possible_countries(country,population) VALUES ('Moldova',2706049);
INSERT INTO possible_countries(country,population) VALUES ('Monaco',38682);
INSERT INTO possible_countries(country,population) VALUES ('Mongolia',3170208);
INSERT INTO possible_countries(country,population) VALUES ('Montenegro',631219);
INSERT INTO possible_countries(country,population) VALUES ('Montserrat',5900);
INSERT INTO possible_countries(country,population) VALUES ('Morocco',36029138);
INSERT INTO possible_countries(country,population) VALUES ('Mozambique',29495962);
INSERT INTO possible_countries(country,population) VALUES ('Myanmar',53708395);
INSERT INTO possible_countries(country,population) VALUES ('Namibia',2448255);
INSERT INTO possible_countries(country,population) VALUES ('Nauru',12704);
INSERT INTO possible_countries(country,population) VALUES ('Nepal',28087871);
INSERT INTO possible_countries(country,population) VALUES ('Netherlands',17231624);
INSERT INTO possible_countries(country,population) VALUES ('Netherlands Antilles',227049);
INSERT INTO possible_countries(country,population) VALUES ('New Caledonia',284060);
INSERT INTO possible_countries(country,population) VALUES ('New Zealand',4841000);
INSERT INTO possible_countries(country,population) VALUES ('Nicaragua',6465513);
INSERT INTO possible_countries(country,population) VALUES ('Niger',22442948);
INSERT INTO possible_countries(country,population) VALUES ('Nigeria',195874740);
INSERT INTO possible_countries(country,population) VALUES ('Niue',1624);
INSERT INTO possible_countries(country,population) VALUES ('Norfolk Island',2169);
INSERT INTO possible_countries(country,population) VALUES ('North Korea',25549819);
INSERT INTO possible_countries(country,population) VALUES ('Northern Ireland',1885400);
INSERT INTO possible_countries(country,population) VALUES ('Northern Mariana Islands',56882);
INSERT INTO possible_countries(country,population) VALUES ('Norway',5311916);
INSERT INTO possible_countries(country,population) VALUES ('Oman',4829483);
INSERT INTO possible_countries(country,population) VALUES ('Pakistan',212215030);
INSERT INTO possible_countries(country,population) VALUES ('Palau',17907);
INSERT INTO possible_countries(country,population) VALUES ('Palestine',4569087);
INSERT INTO possible_countries(country,population) VALUES ('Panama',4176873);
INSERT INTO possible_countries(country,population) VALUES ('Papua New Guinea',8606316);
INSERT INTO possible_countries(country,population) VALUES ('Paraguay',6956071);
INSERT INTO possible_countries(country,population) VALUES ('Peru',31989256);
INSERT INTO possible_countries(country,population) VALUES ('Philippines',106651922);
INSERT INTO possible_countries(country,population) VALUES ('Pitcairn',67);
INSERT INTO possible_countries(country,population) VALUES ('Poland',37974750);
INSERT INTO possible_countries(country,population) VALUES ('Portugal',10283822);
INSERT INTO possible_countries(country,population) VALUES ('Puerto Rico',3195153);
INSERT INTO possible_countries(country,population) VALUES ('Qatar',2781677);
INSERT INTO possible_countries(country,population) VALUES ('Reunion',859959);
INSERT INTO possible_countries(country,population) VALUES ('Romania',19466145);
INSERT INTO possible_countries(country,population) VALUES ('Russia',144478050);
INSERT INTO possible_countries(country,population) VALUES ('Rwanda',12301939);
INSERT INTO possible_countries(country,population) VALUES ('Saint Helena',6600);
INSERT INTO possible_countries(country,population) VALUES ('Saint Kitts and Nevis',52441);
INSERT INTO possible_countries(country,population) VALUES ('Saint Lucia',181889);
INSERT INTO possible_countries(country,population) VALUES ('Saint Pierre and Miquelon',5888);
INSERT INTO possible_countries(country,population) VALUES ('Saint Vincent and the Grenadines',110210);
INSERT INTO possible_countries(country,population) VALUES ('Samoa',196130);
INSERT INTO possible_countries(country,population) VALUES ('San Marino',33785);
INSERT INTO possible_countries(country,population) VALUES ('Sao Tome and Principe',211028);
INSERT INTO possible_countries(country,population) VALUES ('Saudi Arabia',33699947);
INSERT INTO possible_countries(country,population) VALUES ('Scotland',5424800);
INSERT INTO possible_countries(country,population) VALUES ('Senegal',15854360);
INSERT INTO possible_countries(country,population) VALUES ('Serbia',6963764);
INSERT INTO possible_countries(country,population) VALUES ('Seychelles',96762);
INSERT INTO possible_countries(country,population) VALUES ('Sierra Leone',7650154);
INSERT INTO possible_countries(country,population) VALUES ('Singapore',5638676);
INSERT INTO possible_countries(country,population) VALUES ('Slovakia',5446771);
INSERT INTO possible_countries(country,population) VALUES ('Slovenia',2073894);
INSERT INTO possible_countries(country,population) VALUES ('Solomon Islands',652858);
INSERT INTO possible_countries(country,population) VALUES ('Somalia',15008154);
INSERT INTO possible_countries(country,population) VALUES ('South Africa',57779622);
INSERT INTO possible_countries(country,population) VALUES ('South Georgia and the South Sandwich Islands',30);
INSERT INTO possible_countries(country,population) VALUES ('South Korea',51606633);
INSERT INTO possible_countries(country,population) VALUES ('South Sudan',10975920);
INSERT INTO possible_countries(country,population) VALUES ('Spain',46796540);
INSERT INTO possible_countries(country,population) VALUES ('Sri Lanka',21670000);
INSERT INTO possible_countries(country,population) VALUES ('Sudan',41801533);
INSERT INTO possible_countries(country,population) VALUES ('Suriname',575991);
INSERT INTO possible_countries(country,population) VALUES ('Svalbard and Jan Mayen',2572);
INSERT INTO possible_countries(country,population) VALUES ('Swaziland',1136191);
INSERT INTO possible_countries(country,population) VALUES ('Sweden',10175214);
INSERT INTO possible_countries(country,population) VALUES ('Switzerland',8513227);
INSERT INTO possible_countries(country,population) VALUES ('Syria',16906283);
INSERT INTO possible_countries(country,population) VALUES ('Tajikistan',9100837);
INSERT INTO possible_countries(country,population) VALUES ('Tanzania',56318348);
INSERT INTO possible_countries(country,population) VALUES ('Thailand',69428524);
INSERT INTO possible_countries(country,population) VALUES ('The Democratic Republic of Congo',84068091);
INSERT INTO possible_countries(country,population) VALUES ('Togo',7889094);
INSERT INTO possible_countries(country,population) VALUES ('Tokelau',1411);
INSERT INTO possible_countries(country,population) VALUES ('Tonga',103197);
INSERT INTO possible_countries(country,population) VALUES ('Trinidad and Tobago',1389858);
INSERT INTO possible_countries(country,population) VALUES ('Tunisia',11565204);
INSERT INTO possible_countries(country,population) VALUES ('Turkey',82319724);
INSERT INTO possible_countries(country,population) VALUES ('Turkmenistan',5850908);
INSERT INTO possible_countries(country,population) VALUES ('Turks and Caicos Islands',37665);
INSERT INTO possible_countries(country,population) VALUES ('Tuvalu',11508);
INSERT INTO possible_countries(country,population) VALUES ('Uganda',42723139);
INSERT INTO possible_countries(country,population) VALUES ('Ukraine',44622516);
INSERT INTO possible_countries(country,population) VALUES ('United Arab Emirates',9630959);
INSERT INTO possible_countries(country,population) VALUES ('United Kingdom',66460344);
INSERT INTO possible_countries(country,population) VALUES ('United States',326687501);
INSERT INTO possible_countries(country,population) VALUES ('Uruguay',3449299);
INSERT INTO possible_countries(country,population) VALUES ('Uzbekistan',32955400);
INSERT INTO possible_countries(country,population) VALUES ('Vanuatu',292680);
INSERT INTO possible_countries(country,population) VALUES ('Venezuela',28870195);
INSERT INTO possible_countries(country,population) VALUES ('Vietnam',95540395);
INSERT INTO possible_countries(country,population) VALUES ('Virgin Islands, British',29802);
INSERT INTO possible_countries(country,population) VALUES ('Virgin Islands, U.S.',106977);
INSERT INTO possible_countries(country,population) VALUES ('Wales',3139000);
INSERT INTO possible_countries(country,population) VALUES ('Wallis and Futuna',15289);
INSERT INTO possible_countries(country,population) VALUES ('Western Sahara',652271);
INSERT INTO possible_countries(country,population) VALUES ('Yemen',28498687);
INSERT INTO possible_countries(country,population) VALUES ('Zambia',17351822);
INSERT INTO possible_countries(country,population) VALUES ('Zimbabwe',14439018);
